/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package com.shansown.spark

import com.shansown.common.KtorClientApi
import com.shansown.common.delay
import com.shansown.common.retrofitClientApi
import kotlinx.coroutines.delay
import kotlinx.coroutines.runBlocking
import org.slf4j.LoggerFactory
import spark.Spark.port
import spark.Spark.post

private val log = LoggerFactory.getLogger("Spark")

fun main(args: Array<String>) {
  port(8001)

  post("/echo-sync") { req, _ ->
    log.info("---> ${req.body()}")
    Thread.sleep(delay)
    log.info("<--- ${req.body()}")
    req.body()
  }
  post("/echo-async") { req, _ ->
    log.info("---> ${req.body()}")
    runBlocking {
      delay(delay)
      log.info("<--- ${req.body()}")
      req.body()
    }
  }
  post("/network-sync") { req, _ ->
    val payload = req.body()
    log.info("---> $payload")
    val response: String? = retrofitClientApi.payloadSync(payload).execute().body()
    log.info("<--- $response")
    response
  }
  post("/network-async") { req, _ ->
    val payload = req.body()
    log.info("---> $payload")
    val response = runBlocking {
      // TODO: Why is it so SLOW in async???
      // retrofitClient.payloadAsync(req.body())
      KtorClientApi.payload(payload)
    }
    log.info("<--- $response")
    response
  }
}
